project_id = "lenltzlsnlbzwlizmijc"

[functions.create-demo-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.evaluate-code]
verify_jwt = false

